# Generated by Django 4.1 on 2022-08-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_stock_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobille_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('return_note', models.TextField(blank=True, null=True)),
                ('cancel_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.deliverymethod')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Initial', 'Initial'), ('Assigned', 'Assigned'), ('Pending', 'Pending'), ('Return', 'Return'), ('Complete', 'Complete')], default='Initial', max_length=10)),
                ('qty', models.IntegerField()),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.neworder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
